### ISSUE TITLE
[Suggesttions] Features to add

### ISSUE THREAD

**Issue by MrXJKz** [bagnz0r/ichigo-player#26]
Hi, I'm back again! I want somes features on your great player.

• in the "Settings" menu and "Library". can you add the possibility to see what directory I've add? 

• double-click to add music in the current playlist

• in the library at the left, add something like : "gender" "titles" "album" "directory"

• in the "Settings" add an feature to change the "one-click to play", because I make mistake. If I can double-click to change music.

That's all for now. After ~2 hours of playing music, no bug.

**Comment by MrXJKz** [comment]
• drag and drop a file in the player

**Comment by MrXJKz** [comment]
• a dark theme? (i've seen "Themes" in "Settings")

**Comment by bagnz0r** [comment]
All valid suggestions. Will add these over time. :P

**Comment by MrXJKz** [comment]
• possibility to change .mp3, .flac or other audio format to use Ichigo by default.

I haven't any knowledge, I can't do this myself with your source x')

**Comment by bagnz0r** [comment]
New version is coming out on Sunday. I'll add your requested changes except for the genre stuff - as it requires more work.

**Comment by MrXJKz** [comment]
Ok, I'm waiting. ^^
